Ticket #45
jerdbaer/Zeiterfassung pull request #56
Opened 2021-07-18 18:21 UTC by jerdbaer

implemented new calculations & unit tests for these calculation classes
mainly it is about the unit tests which are already done. about calculation code we can discuss. I added a separate Josi.calculation package so nothing will be over written by this merge.

@valientes just creating pull request so we can merge it latest on Sunday after discussing the classes
we can probably combine some classes to one because it's very similar, but let's discuss on Sunday.

2021-07-19 17:24 UTC, valientes requested changes
Overall sachlich gut, es sind nur einige Effizienzsachen dabei. Wichtigster Issue ist in `WorkingTime.java` die Klassenvariable, die so heißt wie ein Parameter einer Klassenmethode

2021-07-19 17:24 UTC, valientes commented on josi/calculation/Break.java
> +	private LocalTime tempBreakDuration;
`tempBreakDuration` muss nicht zwingend eine Klassenvariable sein, das reicht, wenn sie lokal in der Methode `calculateBreakDuration` initialisiert wird

2021-07-19 17:24 UTC, valientes commented on josi/calculation/Break.java
> +		if (breakDuration.compareTo(LEGAL_REQUIREMENT) == 0 || breakDuration.compareTo(LEGAL_REQUIREMENT) > 0) {
Du kannst 3 Zeilen Code entfernen, indem du `return  breakDuration.compareTo(LEGAL_REQUIREMENT) == 0 || breakDuration.compareTo(LEGAL_REQUIREMENT) > 0` schreibst, anstatt das als Bedingung für einen bool-return zu verwenden

2021-07-19 17:24 UTC, valientes commented on josi/calculation/LegalBreak.java
> +		if (valide_Breaktime >= breaktime_min_in_h)
Siehe `Break.java` Zeile 32

2021-07-19 17:24 UTC, valientes commented on josi/calculation/LegalBreak.java
> +
Bitte toten Code entfernen

2021-07-19 17:24 UTC, valientes commented on josi/calculation/MainJosi.java
> +public class MainJosi {
Bitte erinnere mich, dass wir nachher über die Datei und deren Nutzen reden, der erschließt sich mir aktuell leider nicht. Kann aber auch an mir liegen

2021-07-19 17:24 UTC, valientes commented on josi/calculation/TimeAtWork.java
> +	LocalTime tempTimeAtWork;
Auch da können wir die temporäre Variable nur lokal in der Methode definieren (siehe `Break.java` Zeile 11)

2021-07-19 17:24 UTC, valientes commented on josi/calculation/TotalTimeAtWork.java
> +	LocalTime tempTotalTimeAtWork;
Siehe `Break.java` Zeile 11

2021-07-19 17:24 UTC, valientes commented on josi/calculation/WorkingTime.java
> +	TotalTimeAtWork totalTimeAtWork;
Achtung, die Variable heißt so wie ein Methodenparameter eines anderen Typs! Das bitte dringend ändern.

Weiter sehe ich nicht, wo wir diese Klassenvariable nutzen

2021-07-19 17:24 UTC, valientes commented on test/BreakTest.java
> +		LocalTime actualBreak = break1.calculateBreakDuration();
Da musst du nicht zwingend die Methode aufrufen, wenn du deren Ergebnis schon als Klassenvariable gespeichert hast (als `break1.breakDuration`). Da diese sowieso im Konstruktor aufgerufen wird, wird sie in dem Fall zwei mal durchlaufen. Nichtsdestotrotz ist der Test semantisch richtig

2021-07-19 17:24 UTC, valientes commented on test/BreakTest.java
> +		LocalTime actualBreak = break1.calculateBreakDuration();
Siehe Zeile 19

2021-07-19 17:24 UTC, valientes commented on test/BreakTest.java
> +		LocalTime actualBreak = break1.calculateBreakDuration();
Siehe Zeile 19 (ich setze solche Kommentare nur, dass alle betroffenen Stellen korrigiert werden, wenn mein Ursprungskommentar berechtigt ist)

2021-07-19 17:24 UTC, valientes commented on test/BreakTest.java
> +		boolean actuelLegalCompliant = break1.validateLegalCompliance();
Analog zu Zeile 19 ist das hier auch als Klassenvariable gespeichert

2021-07-19 17:24 UTC, valientes commented on test/BreakTest.java
> +		boolean actuelLegalCompliant = break1.validateLegalCompliance();
Siehe Zeile 50

2021-07-19 17:24 UTC, valientes commented on test/BreakTest.java
> +		boolean actuelLegalCompliant = break1.validateLegalCompliance();
Siehe Zeile 50

2021-07-19 17:24 UTC, valientes commented on test/TimeAtWorkTest.java
> +		LocalTime actualTimeAtWork = timeAtWork.calculateTimeAtWork();
Das ist bereits als Klassenvariable gespeichert

2021-07-19 17:24 UTC, valientes commented on test/TimeAtWorkTest.java
> +		LocalTime actualTimeAtWork = timeAtWork.calculateTimeAtWork();
s. Zeile 16

2021-07-19 17:24 UTC, valientes commented on test/TimeAtWorkTest.java
> +		LocalTime actualTimeAtWork = timeAtWork.calculateTimeAtWork();
s. Zeile 16

2021-07-19 17:24 UTC, valientes commented on test/TimeAtWorkTest.java
> +		LocalTime actualTimeAtWork = timeAtWork.calculateTimeAtWork();
s. Zeile 16

2021-07-19 17:24 UTC, valientes commented on test/TotalTimeAtWorkTest.java
> +		LocalTime actualTotalTime = total.calculateTotalTimeAtWork();
Das ist bereits als Klassenvariable berechnet worden

2021-07-19 17:24 UTC, valientes commented on test/TotalTimeAtWorkTest.java
> +		LocalTime actualTotalTime = total.calculateTotalTimeAtWork();
s. Zeile 24

2021-07-19 17:24 UTC, valientes commented on test/TotalTimeAtWorkTest.java
> +		LocalTime actualTotalTime = total.calculateTotalTimeAtWork();
s. Zeile 24

2021-07-19 17:24 UTC, valientes commented on test/TotalTimeAtWorkTest.java
> +		LocalTime actualTotalTime = total.calculateTotalTimeAtWork();
s. Zeile 24

2021-07-19 17:24 UTC, valientes commented on josi/calculation/WorkingTime.java
> +			return workingTime = LocalTime.of(0,0);
unnötige Zuweisung

2021-07-19 18:12 UTC, TomxHWRxWI20C requested changes
Hope u see the inline comments
overall looks good but i have some suggestions ^^

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/Break.java
> +	public LocalTime calculateBreakDuration() {
there exists a Class in Java called Duration, it does exaktly the same if u give it start- and endtime but it saves the duration ISO conform.

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/LegalBreak.java
> +
maby save the whole sentence in the if statement in an boolean varible 
( boolean isTotalTimeAtWorkOver6hoursButUnder9Hours = totalTimeAtWork.compareTo(TOTAL_TIME_OVER_6HOURS) == 0 || 
				totalTimeAtWork.compareTo(TOTAL_TIME_OVER_6HOURS) > 0 &&
				totalTimeAtWork.compareTo(TOTAL_TIME_OVER_9HOURS) < 0) )
for readability.

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/LegalBreak.java
> +
deleat the Zombiecode before u merge

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/LegalBreak.java
> +
this needs an replacement we will work with java.time. The Sum of all breaks has to be in LocalTime

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/LegalBreak.java
> +
this needs an replacement we will work with java.time. The Validation of all breaks has to be in LocalTime

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/TotalTimeAtWork.java
> +
in the method calculateTotalTimeAtWork u need to pass in timeAtworkList

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/TotalTimeAtWork.java
> +
consider HashMap<String, LocalTime> instead of ArrayList for better naming

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/MainJosi.java
> +
deleat Zombie code

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/MainJosi.java
> +
don't know what this is -.-

2021-07-19 18:12 UTC, TomxHWRxWI20C commented on josi/calculation/MainJosi.java
> +
add variables for example for "totalTimeAtWork.compareTo(TOTAL_TIME_OVER_6HOURS) == 0
				|| totalTimeAtWork.compareTo(TOTAL_TIME_OVER_6HOURS) > 0
						&& totalTimeAtWork.compareTo(TOTAL_TIME_OVER_9HOURS) < 0" 
to increase readability

2021-07-19 18:18 UTC, valientes commented on josi/calculation/LegalBreak.java
> +
I honestly don't know if it really helps, you just shift the readability issue with this

2021-07-22 20:44 UTC, valientes commented
In Absprache mit @jerdbaer und @TomxHWRxWI20C

2021-07-22 20:44 UTC, closed without merging