Toms controllers + simons exceotions java docs
jerdbaer/Zeiterfassung pull request #95
Opened 2021-07-27 18:26 UTC by jerdbaer

2021-07-27 19:57 UTC, TomxHWRxWI20C requested changes
only small change looks very good
nice one

2021-07-27 19:57 UTC, TomxHWRxWI20C commented on controller/MainViewInputRestrictionController.java
> + */
This provides rules to restrict the possible Keyinput (includes Strg+V or Mouse copy)  in Textfields
- only Numbers
- only hours (0-23)
- only minutes(0-59)

2021-07-27 19:57 UTC, TomxHWRxWI20C commented on controller/OverviewController.java
> +     */
change earlier month to random data

2021-07-27 19:57 UTC, TomxHWRxWI20C commented on controller/PopupDoubleEntryController.java
> +     */
this overwrites the old entry too

2021-07-27 19:57 UTC, TomxHWRxWI20C commented on controller/PopupLimitsController.java
> + *
this is wrong 
this part is for workinglimits 
popup to add comment why worked so early / late

2021-07-27 19:57 UTC, TomxHWRxWI20C commented on controller/SwapSceneController.java
>      	}
needs to be deleted 
we don't want the methode goToLogin()

2021-07-28 02:56 UTC, TomxHWRxWI20C approved these changes

2021-07-28 09:20 UTC, valientes approved these changes

2021-07-28 09:45 UTC, merged